# Generated by Django 5.1.7 on 2025-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_exercise_correction_models_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='correction_models_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='file_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='correction_models',
            field=models.FileField(blank=True, null=True, upload_to='corrections/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
