# Generated by Django 5.1.7 on 2025-03-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exercise_correction_models_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(default='default_file.txt', upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
